#!/usr/bin/env python3
"""Extract current POSIX TZ rules from the system tzdata.

Writes tzdata.csv (the data file; an SD-card copy is planned to override
the embedded table) and tzdata.h (the embedded fallback, generated from
the same rows). Re-run after a tzdata update and reflash.
"""

import os


def zoneinfo_dir():
    # Prefer the upstream IANA tzdata package (run: uv run --with tzdata
    # python3 gen_tzdata.py) — macOS's own zoneinfo has broken footers
    # (e.g. America/Vancouver claiming MST7).
    try:
        import tzdata

        path = os.path.join(os.path.dirname(tzdata.__file__), "zoneinfo")
        if os.path.isdir(path):
            return path
    except ImportError:
        pass
    return "/usr/share/zoneinfo"


ZDIR = zoneinfo_dir()
SKIP = {
    "posixrules", "localtime", "Factory", "leapseconds", "tzdata.zi",
    "zone.tab", "zone1970.tab", "iso3166.tab", "leap-seconds.list",
    "+VERSION", "SECURITY", "README",
}


def footer(path):
    with open(path, "rb") as f:
        data = f.read()
    if not data.startswith(b"TZif") or data.count(b"\n") < 2:
        return None
    end = data.rfind(b"\n")
    start = data.rfind(b"\n", 0, end)
    return data[start + 1:end].decode("ascii", "ignore").strip() or None


rows = []
for root, _dirs, files in os.walk(ZDIR, followlinks=False):
    for fn in files:
        path = os.path.join(root, fn)
        name = os.path.relpath(path, ZDIR)
        if name in SKIP or name.startswith(("posix/", "right/", "__")):
            continue
        if fn.endswith((".py", ".pyc")) or "__pycache__" in name:
            continue
        try:
            tz = footer(path)
        except OSError:
            continue
        if tz:
            rows.append((name, tz))
rows.sort()

with open("tzdata.csv", "w") as f:
    for name, tz in rows:
        f.write(f"{name},{tz}\n")

with open("tzdata.h", "w") as f:
    f.write(
        "#pragma once\n\n"
        "// Generated by gen_tzdata.py — current POSIX rules per IANA zone,\n"
        "// no historical transitions. Source of truth: tzdata.csv.\n\n"
        "namespace reterminal {\n\n"
        "struct TzEntry {\n"
        "  const char *name;\n"
        "  const char *posix;\n"
        "};\n\n"
        "static const TzEntry TZDATA[] = {\n"
    )
    for name, tz in rows:
        f.write(f'    {{"{name}", "{tz}"}},\n')
    f.write(
        "};\n\n"
        "constexpr int TZDATA_COUNT = sizeof(TZDATA) / sizeof(TZDATA[0]);\n\n"
        "}  // namespace reterminal\n"
    )

print(f"{len(rows)} zones")
