"""reTerminal E1001 dashboard: the C++ behind the YAML lambdas, and the
build inputs git cannot carry (dial photos, the version stamp).

The C++ lives in src/ rather than beside this file: ESPHome includes every
header in a component's folder into every translation unit, and these
headers define globals. Copied into the build and included once from
main.cpp, as `esphome: includes:` would, they are defined exactly once.
"""

import io
from pathlib import Path
import subprocess

from PIL import Image, ImageEnhance, ImageOps
import requests

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.core import CORE, CoroPriority, coroutine_with_priority
from esphome.core.config import include_file
from esphome.helpers import walk_files, write_file_if_changed

CODEOWNERS = ["@mehdisadeghi"]

SRC = Path(__file__).parent / "src"
CONF_DIAL_IMAGES = "dial_images"
# single-dial diameter (R=197), the largest a face can render
MAX_SIDE = 394
# brightness/contrast lift that keeps a photo legible once dithered to 1 bit
BRIGHTNESS = 1.18
CONTRAST = 1.15
FETCH_TIMEOUT_S = 30

CONFIG_SCHEMA = cv.Schema(
    {
        # city (a zone's last IANA segment, lowercased) -> URL or local path
        cv.Optional(CONF_DIAL_IMAGES, default={}): cv.Schema(
            {cv.string_strict: cv.string_strict}
        ),
    }
)


def _read_image(source: str) -> Image.Image:
    if source.startswith(("http://", "https://")):
        resp = requests.get(source, timeout=FETCH_TIMEOUT_S)
        resp.raise_for_status()
        return Image.open(io.BytesIO(resp.content))
    return Image.open(CORE.relative_config_path(source))


def _dial_images_h(images: dict[str, str]) -> str:
    out = [
        "#pragma once\n",
        "// Generated by the reterminal component from its dial_images config.",
        "// Dial face photos as pre-adjusted grayscale squares (flash-resident).\n",
        "#include <cstdint>\n\nnamespace reterminal {\n",
        "struct DialSrc {\n  const char *name;  // lowercased IANA city\n"
        "  int side;\n  const uint8_t *gray;  // side*side bytes, row-major\n};\n",
    ]
    rows = []
    for name, source in sorted(images.items()):
        name = name.lower()
        img = _read_image(source)
        side = min(MAX_SIDE, *img.size)
        img = ImageOps.fit(img.convert("L"), (side, side))
        img = ImageEnhance.Brightness(img).enhance(BRIGHTNESS)
        img = ImageEnhance.Contrast(img).enhance(CONTRAST)
        data = img.tobytes()
        out.append(f"static const uint8_t DIAL_GRAY_{name.upper()}[{len(data)}] = {{")
        out.extend(",".join(map(str, data[i : i + 24])) + "," for i in range(0, len(data), 24))
        out.append("};\n")
        rows.append(f'    {{"{name}", {side}, DIAL_GRAY_{name.upper()}}},')
    # a zero-length array is not valid C++; the null entry is never matched
    rows.append('    {"", 0, nullptr},')
    out.append("static const DialSrc DIAL_SRCS[] = {")
    out.extend(rows)
    out.append("};")
    out.append(f"constexpr int DIAL_SRC_COUNT = {len(images)};\n")
    out.append("}  // namespace reterminal\n")
    return "\n".join(out)


def _version() -> str:
    return subprocess.run(
        ["git", "describe", "--tags", "--always", "--dirty"],
        cwd=SRC,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


# FINAL: after the core has emitted the project defines this replaces, and
# after the Arduino glue the included code relies on
@coroutine_with_priority(CoroPriority.FINAL)
async def to_code(config):
    for path in sorted(walk_files(SRC)):
        include_file(path, path.relative_to(SRC))
    write_file_if_changed(
        CORE.relative_src_path("reterminal", "dial_images.h"),
        _dial_images_h(config[CONF_DIAL_IMAGES]),
    )
    # the yaml's project version is a placeholder: a build from a remote
    # package cannot run git itself, so the version comes from this source
    version = _version()
    CORE.defines = {
        d
        for d in CORE.defines
        if d.name not in ("ESPHOME_PROJECT_VERSION", "ESPHOME_PROJECT_VERSION_30")
    }
    cg.add_define("ESPHOME_PROJECT_VERSION", version)
    cg.add_define("ESPHOME_PROJECT_VERSION_30", version[:29])
