#!/usr/bin/env python3
"""Generate the Persian UI string table and its font glyph list.

Shapes tools/translations_fa.yaml (contextual forms, lam-alef) and
reorders to visual order, like gen_fa_assets.py does for the Khayyam
corpus — so the firmware prints plain strings with no shaping engine.
ZWNJ is dropped after shaping (it has done its job by then and has no
glyph). Emits:

    reterminal-e1001/reterminal/strings_fa.h   constants + tables
    reterminal-e1001/reterminal/arabic_forms.h contextual-form table for the
                                               on-device shaper (labels)
    reterminal-e1001/fa_ui_glyphs.yaml         glyph list for the UI fonts

Run from the repo root: `uv run tools/gen_fa_strings.py`.
"""
# /// script
# requires-python = ">=3.11"
# dependencies = ["arabic-reshaper", "python-bidi", "fonttools", "pyyaml", "babel"]
# ///

import sys

import arabic_reshaper
import arabic_reshaper.letters as letters
import yaml
from babel import Locale
from babel.dates import get_timezone_location
from bidi.algorithm import get_display
from fontTools.ttLib import TTFont

ASCII = ('!"%()+,-./0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ_'
         "abcdefghijklmnopqrstuvwxyz °")
FA_EXTRA = "۰۱۲۳۴۵۶۷۸۹٫٪"  # Persian digits, momayyez, percent

reshaper = arabic_reshaper.ArabicReshaper({"delete_harakat": False,
                                           "support_ligatures": True})


def shape(s):
    return get_display(reshaper.reshape(s)).replace("‌", "")


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


doc = yaml.safe_load(open("tools/translations_fa.yaml", encoding="utf-8"))
strings = {k: shape(v) for k, v in doc["strings"].items()}
tables = {name: [shape(v) for v in doc[name]]
          for name in ("weekdays", "months_gregorian", "months_jalali",
                       "months_hijri", "zodiac")}

# CLDR exemplar city names for every zone in the embedded table, so the
# clock pages show Persian city names without anyone typing Persian.
FA = Locale("fa")


def arabic_script(s):
    return any(0x0600 <= ord(c) <= 0x06FF or 0xFB50 <= ord(c) <= 0xFEFF for c in s)


cities = []
with open("tzdata.csv", encoding="ascii") as f:
    for line in f:
        name = line.split(",", 1)[0].strip()
        if not name:
            continue
        try:
            city = get_timezone_location(name, locale=FA, return_city=True)
        except Exception:
            continue
        if city and arabic_script(city):
            cities.append((name, shape(city)))
cities.sort()

# Contextual-form table for the on-device shaper: same source data as the
# build-time reshaper, so both agree glyph for glyph.
cmap = TTFont("reterminal-e1001/vazirmatn.ttf").getBestCmap()
# only letters whose forms the font can render (drops Urdu/Kurdish extras)
FORMS = {ord(ch): tuple(ord(f) if f else 0 for f in forms)
         for ch, forms in letters.LETTERS_ARABIC.items()
         if len(ch) == 1
         and all(ord(f) in cmap for f in forms if f)}
LAM_ALEF = [(0x0622, 0xFEF5, 0xFEF6), (0x0623, 0xFEF7, 0xFEF8),
            (0x0625, 0xFEF9, 0xFEFA), (0x0627, 0xFEFB, 0xFEFC)]

charset = set(ASCII) | set(FA_EXTRA)
for forms in FORMS.values():
    charset |= {chr(f) for f in forms if f}
for _, iso, fin in LAM_ALEF:
    charset |= {chr(iso), chr(fin)}
for v in strings.values():
    charset |= set(v)
for t in tables.values():
    for v in t:
        charset |= set(v)
for _, v in cities:
    charset |= set(v)
charset.discard("\n")

missing = sorted(c for c in charset if ord(c) not in cmap)
if missing:
    sys.exit(f"vazirmatn.ttf lacks glyphs: {missing!r}")

with open("reterminal-e1001/fa_ui_glyphs.yaml", "w", encoding="utf-8") as f:
    f.write("# Generated by tools/gen_fa_strings.py — do not edit.\n")
    for c in sorted(charset):
        f.write(f'- "{cesc(c)}"\n')

with open("reterminal-e1001/reterminal/strings_fa.h", "w", encoding="utf-8") as f:
    f.write(
        "#pragma once\n\n"
        "// Generated by tools/gen_fa_strings.py from translations_fa.yaml —\n"
        "// pre-shaped presentation forms in visual order. Data only; the\n"
        "// language registry lives in lang.h. Do not edit.\n\n"
        "namespace lang {\n"
        "namespace fa {\n\n")
    for k, v in strings.items():
        f.write(f'constexpr const char *{k} = "{cesc(v)}";\n')
    f.write("\n")
    for name, cname in (("weekdays", "WEEKDAYS"), ("months_gregorian", "MONTHS"),
                        ("months_jalali", "JMONTHS"), ("months_hijri", "HMONTHS"),
                        ("zodiac", "ZODIAC")):
        vals = ", ".join(f'"{cesc(v)}"' for v in tables[name])
        f.write(f"static const char *const {cname}[{len(tables[name])}] = {{{vals}}};\n")
    f.write("\n// CLDR exemplar cities (shaped); zones without a Persian name fall\n"
            "// back to their configured label.\n"
            "struct City {\n  const char *iana;\n  const char *name;\n};\n"
            f"static const City CITIES[{len(cities)}] = {{\n")
    for iana, name in cities:
        f.write(f'    {{"{iana}", "{cesc(name)}"}},\n')
    f.write("};\n"
            f"constexpr int CITY_COUNT = {len(cities)};\n")
    f.write("\n}  // namespace fa\n}  // namespace lang\n")

with open("reterminal-e1001/reterminal/arabic_forms.h", "w", encoding="utf-8") as f:
    f.write(
        "#pragma once\n\n"
        "// Generated by tools/gen_fa_strings.py from arabic-reshaper's letter\n"
        "// data — contextual presentation forms for the on-device shaper\n"
        "// (arabic_shape.h). 0 = form unavailable. Do not edit.\n\n"
        "#include <cstdint>\n\n"
        "namespace reterminal {\n\n"
        "struct ArabicForms {\n"
        "  uint32_t base;\n"
        "  uint32_t iso, ini, med, fin;\n"
        "};\n\n"
        f"static const ArabicForms ARABIC_FORMS[{len(FORMS)}] = {{\n")
    for base in sorted(FORMS):
        iso, ini, med, fin = FORMS[base]
        f.write(f"    {{0x{base:04X}, 0x{iso:04X}, 0x{ini:04X}, 0x{med:04X}, 0x{fin:04X}}},\n")
    f.write("};\n"
            f"constexpr int ARABIC_FORM_COUNT = {len(FORMS)};\n\n"
            "struct LamAlef {\n  uint32_t alef;\n  uint32_t iso, fin;\n};\n\n"
            f"static const LamAlef LAM_ALEF[{len(LAM_ALEF)}] = {{\n")
    for alef, iso, fin in LAM_ALEF:
        f.write(f"    {{0x{alef:04X}, 0x{iso:04X}, 0x{fin:04X}}},\n")
    f.write("};\n"
            f"constexpr int LAM_ALEF_COUNT = {len(LAM_ALEF)};\n\n"
            "}  // namespace reterminal\n")

print(f"{len(strings)} strings, {len(cities)} cities, {len(FORMS)} form rows, "
      f"{len(charset)} glyphs")
