#!/usr/bin/env python3
"""Embed subset TrueType faces for the on-device rasterizer.

The status bar's type size is a user setting, and ESPHome bakes every font
size at build time — so a fixed ladder of sizes was the only way to offer
more than one. Instead the outlines themselves ride along and the device
rasterizes at whatever size is asked for (reterminal/ttf_font.h).

Only the glyphs the UI can actually draw are kept, and the shaping tables
go: Persian is pre-shaped into presentation forms by gen_fa_strings.py, so
GSUB/GPOS would never be consulted. Emits:

    reterminal-e1001/reterminal/ttf_data.h   subset faces as byte arrays

Run from the repo root: `uv run tools/gen_ttf.py`.
"""
# /// script
# requires-python = ">=3.11"
# dependencies = ["fonttools", "pyyaml"]
# ///

import io

import yaml
from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

# Same coverage as the compiled faces in packages/fonts.yaml; the Persian
# list is generated, so it stays in step with the strings on its own.
ASCII = ('!"%()+,-./0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ_'
         "abcdefghijklmnopqrstuvwxyz °")
FA_EXTRA = "۰۱۲۳۴۵۶۷۸۹٫٪"

FACES = [
    ("INTER_BOLD", "reterminal-e1001/inter-bold.ttf", None),
    ("VAZIRMATN", "reterminal-e1001/vazirmatn.ttf", "reterminal-e1001/fa_ui_glyphs.yaml"),
]


def subset(path, chars):
    # keep the source timestamp: a regenerated header must not dirty the tree
    font = TTFont(path, recalcTimestamp=False)
    opts = Options()
    opts.layout_features = []          # text arrives pre-shaped
    opts.drop_tables += ["GSUB", "GPOS", "GDEF", "kern", "morx", "DSIG"]
    opts.hinting = False               # stb_truetype ignores hints anyway
    opts.desubroutinize = True
    opts.name_IDs = []
    sub = Subsetter(options=opts)
    sub.populate(unicodes=sorted({ord(c) for c in chars}))
    sub.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue(), font


out = ["// Generated by tools/gen_ttf.py — do not edit.",
       "#pragma once", "", "#include <cstdint>", "",
       "namespace reterminal {", ""]
total = 0
for name, path, glyph_list in FACES:
    chars = set(ASCII)
    if glyph_list:
        chars |= set(FA_EXTRA)
        chars |= {g for g in yaml.safe_load(open(glyph_list, encoding="utf-8")) if g}
    data, font = subset(path, chars)
    total += len(data)
    kind = "CFF" if "CFF " in font else "glyf"
    print(f"{path.split('/')[-1]:20s} {len(chars):4d} chars -> {len(data) / 1024:6.1f} KB ({kind})")
    out.append(f"// {path} — {len(chars)} glyphs, {kind} outlines")
    out.append(f"alignas(4) inline constexpr uint8_t {name}_TTF[] = {{")
    for i in range(0, len(data), 16):
        out.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 16]))
    out.append("};")
    out.append("")
out.append("}  // namespace reterminal")

dest = "reterminal-e1001/reterminal/ttf_data.h"
open(dest, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"-> {dest} ({total / 1024:.1f} KB of outlines)")
