# /// script
# requires-python = ">=3.11"
# ///
"""Regenerate the Iranian Islamic calendar table (hijri_ir.h).

The official Iranian lunar calendar is sighting-based and cannot be
computed — the persian-calendar project distributes it as data (12
month-length bits per Hijri year). This pulls their converter source and
emits it as a C table; outside the covered window the firmware falls back
to the tabular calendar. Re-run when upstream extends the table.
"""

import re
import sys
import urllib.request
from pathlib import Path

URL = ("https://raw.githubusercontent.com/persian-calendar/calendar/main/"
       "src/main/kotlin/io/github/persiancalendar/calendar/islamic/"
       "IranianIslamicDateConverter.kt")

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "reterminal-e1001" / "reterminal" / "hijri_ir.h"

src = (Path(sys.argv[1]).read_text() if len(sys.argv) > 1
       else urllib.request.urlopen(URL).read().decode())

start_jdn = int(re.search(r"SUPPORTED_START_JDN = ([\d_]+)L", src).group(1).replace("_", ""))
rows = re.findall(r"/\*(\d+)\*/ (0b[01_]+),", src)
years = [int(y) for y, _ in rows]
masks = [int(m.replace("_", ""), 2) for _, m in rows]
assert years == list(range(years[0], years[0] + len(years))), "non-contiguous years"

with open(OUT, "w") as f:
    f.write("#pragma once\n\n")
    f.write("// Generated by tools/gen_hijri_ir.py from the persian-calendar\n")
    f.write("// project's Iranian Islamic table - do not edit. 12 bits per Hijri\n")
    f.write("// year, bit (11 - month) set = 30-day month, else 29.\n\n")
    f.write("#include <cstdint>\n\nnamespace hijri {\n\n")
    f.write(f"constexpr long IR_START_JDN = {start_jdn};\n")
    f.write(f"constexpr int IR_START_YEAR = {years[0]};\n")
    f.write(f"constexpr int IR_YEARS = {len(years)};\n\n")
    f.write("static const uint16_t IR_MONTHS[IR_YEARS] = {\n")
    for i in range(0, len(masks), 8):
        f.write("    " + ", ".join(f"0x{m:03x}" for m in masks[i : i + 8]) + ",\n")
    f.write("};\n\n}  // namespace hijri\n")
print(f"-> {OUT.relative_to(ROOT)}: {years[0]}..{years[-1]} AH from JDN {start_jdn}")
