#!/usr/bin/env python3
"""Pre-shape the Persian Khayyam corpus into device-ready assets.

Shaping (contextual forms, lam-alef) and RTL ordering happen here at build
time, so the firmware just prints the resulting presentation-form strings.
Run from the repo root: `uv run tools/gen_fa_assets.py [khayyam_fa.yaml]`.

Outputs:
    reterminal/khayyam_fa.h  shaped quatrains + title (visual order, UTF-8)
    fa_glyphs.yaml           exact glyph list for the body font
    fa_title_glyphs.yaml     glyph list for the title font

Every emitted character is verified against the fonts' cmaps; missing
glyphs fail the build loudly.
"""
# /// script
# requires-python = ">=3.11"
# dependencies = ["arabic-reshaper", "python-bidi", "fonttools", "pyyaml"]
# ///

import sys

import arabic_reshaper
import yaml
from bidi.algorithm import get_display
from fontTools.ttLib import TTFont

CORPUS = sys.argv[1] if len(sys.argv) > 1 else "../righter/src/lib/data/khayyam_fa.yaml"
BODY_FONT = "reterminal-e1001/vazirmatn.ttf"
TITLE_FONT = "reterminal-e1001/noqte.ttf"

reshaper = arabic_reshaper.ArabicReshaper({"delete_harakat": False, "support_ligatures": True})


def shape(line):
    visual = get_display(reshaper.reshape(line.strip()))
    return visual.replace("‌", "").replace("‏", "")


def cmap_of(path):
    return set(TTFont(path).getBestCmap().keys())


def check_coverage(chars, cmap, font, what):
    missing = sorted(c for c in chars if c != " " and ord(c) not in cmap)
    if missing:
        sys.exit(f"ERROR: {font} lacks glyphs for {what}: "
                 + " ".join(f"U+{ord(c):04X}" for c in missing))


def main():
    doc = yaml.safe_load(open(CORPUS, encoding="utf-8"))
    title = shape(doc.get("title", "رباعیات خیام"))
    quatrains = []
    for entry in doc["texts"]:
        rows = [l for l in entry["text"].splitlines() if l.strip()]
        if len(rows) != 4:
            print(f"WARNING: skipping #{entry.get('number')}: {len(rows)} lines")
            continue
        quatrains.append([shape(l) for l in rows])
    if not quatrains:
        sys.exit("ERROR: no quatrains")

    body_chars = sorted({c for q in quatrains for l in q for c in l})
    title_chars = sorted(set(title))
    check_coverage(body_chars, cmap_of(BODY_FONT), BODY_FONT, "the corpus")
    check_coverage(title_chars, cmap_of(TITLE_FONT), TITLE_FONT, "the title")

    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')

    with open("reterminal-e1001/reterminal/khayyam_fa.h", "w", encoding="utf-8") as f:
        f.write("#pragma once\n\n"
                "// Generated by gen_fa_assets.py from khayyam_fa.yaml: quatrains\n"
                "// pre-shaped into presentation forms, lines in visual (RTL) order.\n\n"
                "namespace reterminal {\n\n"
                "struct Quatrain {\n  const char *l[4];\n};\n\n"
                "static const Quatrain KHAYYAM_FA[] = {\n")
        for q in quatrains:
            f.write("    {{" + ", ".join(f'"{esc(l)}"' for l in q) + "}},\n")
        f.write("};\n\n"
                f"constexpr int KHAYYAM_COUNT = {len(quatrains)};\n\n"
                f'static const char *const KHAYYAM_TITLE = "{esc(title)}";\n\n'
                "}  // namespace reterminal\n")

    for path, chars in (("reterminal-e1001/fa_glyphs.yaml", body_chars),
                        ("reterminal-e1001/fa_title_glyphs.yaml", title_chars)):
        with open(path, "w", encoding="utf-8") as f:
            f.write("# generated by gen_fa_assets.py\n")
            for c in chars:
                f.write(f'- "{c}"\n' if c != '"' else "- '\"'\n")

    print(f"{len(quatrains)} quatrains, {len(body_chars)} body glyphs, "
          f"{len(title_chars)} title glyphs")


if __name__ == "__main__":
    main()
