# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow"]
# ///
"""Bake dial face photos into the firmware.

Every <city>.png in the images directory (city = a zone's last IANA
segment, lowercased: Europe/Berlin -> berlin.png) becomes a pre-adjusted
grayscale square in components/reterminal/src/reterminal/dial_images.h. The device
scales and dithers it to the dial's radius at draw time (dial_image.h).

The directory comes from argv[1], default repo root (make IMAGES=dir).
The set is shared by every unit; a unit's own faces come from its SD card.
"""

import sys
from pathlib import Path

from PIL import Image, ImageEnhance, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT
OUT = ROOT / "components" / "reterminal" / "src" / "reterminal" / "dial_images.h"
MAX_SIDE = 394  # single-dial diameter (R=197), the largest a face can render

srcs = []
for png in sorted(SRC_DIR.glob("*.png")):
    name = png.stem.lower()
    img = Image.open(png)
    side = min(MAX_SIDE, *img.size)
    img = ImageOps.fit(img.convert("L"), (side, side))
    img = ImageEnhance.Brightness(img).enhance(1.18)
    img = ImageEnhance.Contrast(img).enhance(1.15)
    srcs.append((name, side, img.tobytes()))
    print(f"{png.name}: {side}x{side}")

with open(OUT, "w") as f:
    f.write("#pragma once\n\n")
    f.write("// Generated by tools/gen_dial_images.py - do not edit.\n")
    f.write("// Dial face photos as pre-adjusted grayscale squares (flash-resident).\n\n")
    f.write("#include <cstdint>\n\nnamespace reterminal {\n\n")
    f.write("struct DialSrc {\n  const char *name;  // lowercased IANA city\n")
    f.write("  int side;\n  const uint8_t *gray;  // side*side bytes, row-major\n};\n\n")
    for name, side, data in srcs:
        f.write(f"static const uint8_t DIAL_GRAY_{name.upper()}[{len(data)}] = {{\n")
        for i in range(0, len(data), 24):
            f.write(",".join(str(b) for b in data[i : i + 24]) + ",\n")
        f.write("};\n\n")
    f.write("static const DialSrc DIAL_SRCS[] = {\n")
    for name, side, _ in srcs:
        f.write(f'    {{"{name}", {side}, DIAL_GRAY_{name.upper()}}},\n')
    f.write("};\n")
    f.write(f"constexpr int DIAL_SRC_COUNT = {len(srcs)};\n\n")
    f.write("}  // namespace reterminal\n")
print(f"-> {OUT.relative_to(ROOT)} ({len(srcs)} images)")
